# Generated by Django 5.2.1 on 2025-06-03 07:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=20, unique=True)),
                ('device_type', models.CharField(max_length=100)),
                ('device_brand', models.CharField(max_length=100)),
                ('installation_date', models.DateField(default=django.utils.timezone.now)),
                ('warranty_expiry', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
