# Generated by Django 5.2.1 on 2025-06-05 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('installed', 'Installed'), ('deactivated', 'Deactivated'), ('in_progress', 'In progress')], default='installed', max_length=20),
        ),
    ]
